# This is a default TOML config for the test harness.
# WIP

title = "LP test harness"
local = true
livepeerBinaryPath = "./livepeer"

[blockchain]
  networkId = 54321
  controllerAddress = "0x93ad00a63b14492386df9f1cc123d785705bdf99"

[nodes.transcoders]
  instances = 1
  flags = "--v 4"
[nodes.orchestrators]
  instances = 1
  flags = "--v 4"
[nodes.broadcasters]
  instances = 1
  flags = "--v 4"
