{
 "title": "Livepeer Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Orchestrators Utilisation",
   "type": "gauge",
   "description": "Percentage of streams running on Orchestrators to maxSessions of Orchestrator",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "livepeer_current_sessions_total{node_type=\"orch\"} / livepeer_max_sessions_total{node_type=\"orch\"} * 100"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcoded_appeared_total) by (instance) / on (instance) livepeer_segment_source_emerged_with_profiles_total * 100\nand \nsum(rate(livepeer_segment_transcoded_appeared_total[1m])) by (instance) > 0.01"
    }
   ]
  },
  {
   "title": "Concurrent Streams",
   "type": "singlestat",
   "description": "Number of concurrent streams across all broadcasters",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(livepeer_current_sessions_total{node_type=\"bctr\"})"
    }
   ]
  },
  {
   "title": "Success Rate (Client)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "livepeer_success_rate * 100" }
   ]
  },
  {
   "title": "Success rate 1 minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_segment_transcoded_appeared_total[1m])) / sum(rate(livepeer_segment_source_emerged_with_profiles_total[1m])) * 100"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "description": "Latency is calculated on Broadcaster, from time source segment goes out from segmenter till transcoded segment gets inserted into manifest.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(livepeer_transcode_latency_seconds_sum{node_type=\"bctr\"}[1m])) by (instance) / sum(rate(livepeer_transcode_latency_seconds_count{node_type=\"bctr\"}[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Average Transcode Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(livepeer_transcode_time_seconds_sum{node_type=\"orch\"}[1m]) / rate(livepeer_transcode_time_seconds_count{node_type=\"orch\"}[1m])"
    }
   ]
  },
  {
   "title": "Transcode Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_transcode_failed_total[1m])) by (error_code)"
    }
   ]
  },
  {
   "title": "Upload Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(livepeer_segment_source_upload_failed_total[1m])) by (error_code)"
    }
   ]
  },
  {
   "title": "Transcode Errors Raw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_transcode_failed_total) by (instance, error_code)"
    }
   ]
  },
  {
   "title": "Upload Errors Raw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(livepeer_segment_source_upload_failed_total) by (instance, error_code)"
    }
   ]
  }
 ]
}