{
 "title": "Livepeer Payments Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "# Tickets Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "# Tickets" }
   ],
   "targets": [
    { "expr": "livepeer_tickets_sent" }
   ]
  },
  {
   "title": "# Tickets Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "# Tickets" }
   ],
   "targets": [
    { "expr": "livepeer_tickets_recv" }
   ]
  },
  {
   "title": "Ticket Value (EV) Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ETH (gwei)" }
   ],
   "targets": [
    { "expr": "livepeer_ticket_value_sent" }
   ]
  },
  {
   "title": "Ticket Value (EV) Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ETH (gwei)" }
   ],
   "targets": [
    { "expr": "livepeer_ticket_value_recv" }
   ]
  },
  {
   "title": "# Winning Tickets Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "# Winning Tickets" }
   ],
   "targets": [
    { "expr": "livepeer_winning_tickets_recv" }
   ]
  },
  {
   "title": "Value Redeemed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "ETH (gwei)" }
   ],
   "targets": [
    { "expr": "livepeer_value_redeemed" }
   ]
  },
  {
   "title": "Suggested Gas Price",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "ETH (gwei)" }
   ],
   "targets": [
    { "expr": "livepeer_suggested_gas_price" }
   ]
  },
  {
   "title": "Transcoding Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "ETH (wei)" }
   ],
   "targets": [
    { "expr": "livepeer_transcoding_price" }
   ]
  },
  {
   "title": "Payment Receive Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    { "expr": "livepeer_payment_recv_errors" }
   ]
  },
  {
   "title": "Unacceptable Payment Receive Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    {
     "expr": "livepeer_payment_recv_unacceptable_errors"
    }
   ]
  },
  {
   "title": "Ticket Redemption Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "# Errors" }
   ],
   "targets": [
    {
     "expr": "livepeer_ticket_redemption_errors"
    }
   ]
  }
 ]
}